---

- name: COMMON | update APT cache
  apt: update_cache=yes

- name: COMMON | Install basic packages
  package: name={{ item }} state=present
  with_items:
    - vim
    - curl
    - python-apt
    - drush

- name: COMMON | Remove Apache
  package: name={{ item }} state=absent
  with_items:
    - apache2
    - httpd2
