---
# Webserver Configuration
- name: NGINX | Ensure that nginx PPA is added to Ubuntu
  apt_repository: repo='ppa:nginx/stable'

- name: NGINX | Install nginx
  package: name=nginx state=present update_cache=yes

- name: NGINX | Remove default vhost
  file: path=/etc/nginx/sites-enabled/default state=absent

- name: NGINX | Configure drupal vhost
  template: src=drupal.conf dest=/etc/nginx/conf.d/drupal.conf
  notify:
    - reload nginx

- name: NGINX | nginx should be running, and enabled at boot
  service: name=nginx state=started enabled=yes


