---
- hosts: all
  remote_user: ubuntu
  become_user: root
  become_method: sudo
  become: true
  tasks:
    - name: Run apt update
      apt: update_cache=yes
      
  roles:
  - common
  - database
  - web
  - drupal
