---
- name: reload nginx
  service: name=nginx state=reloaded

- name: reload systemd
  command: systemctl daemon-reload

- name: restart nginx
  service: name=nginx state=restarted
  notify: restart php-fpm

- name: restart php-fpm
  service: name="php{{ php_version }}-fpm" state=restarted
